services:
  flask:
    build:
      context: .
    stop_signal: SIGINT
    ports:
      - '8080:8080'
    volumes:
      - static_volume:/app/app/static:consistent
      - sqlite_db:/app/app/db:consistent
  nginx:
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: backend_nginx
    image: nginx
    volumes:
      - static_volume:/prog-intro-tests-parser/app/static:consistent
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - flask
    ports:
      - "${NGINX_EXTERNAL_PORT:-80}:80"
      - "${NGINX_EXTERNAL_SSL_PORT:-443}:443"

volumes:
  certs:
  vhost:
  static_volume:
  sqlite_db: