services:
  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - ./data/db:/app/app/db:consistent

volumes:
  static_volume:
  sqlite_db: