services:
  flask:
    build:
      context: .
    stop_signal: SIGINT
    ports:
      - '8080:8080'
  nginx:
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: backend_nginx
    image: backend_nginx
    volumes:
      - ./static:/ParkingBackend/static:consistent
      - ./media:/ParkingBackend/media:consistent
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend
    env_file:
      - .env.docker
    ports:
      - "${NGINX_EXTERNAL_PORT:-80}:80"
      - "${NGINX_EXTERNAL_SSL_PORT:-443}:443"