"""empty message

Revision ID: 302a6783318d
Revises: 3d15914e39b1
Create Date: 2024-05-03 20:30:12.149814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302a6783318d'
down_revision = '3d15914e39b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_log', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
